---
# tasks file for jenkins
- name: Removing old version of JAVA from Amazon Linux
  yum:
    name: java-1.7.0-openjdk
    state: absent

- name: Install specific supported version of JAVA
  yum: 
    name: java-1.8.0-openjdk
    state: present

- name: Add Jenkins repository
  shell: wget -O /etc/yum.repos.d/jenkins.repo https://pkg.jenkins.io/redhat-stable/jenkins.repo

- name: Import Jenkins GPG key
  rpm_key:
    state: present
    key: https://pkg.jenkins.io/redhat/jenkins.io.key

- name: Install Jenkins
  yum:
    name: jenkins-2.99
    enablerepo: jenkins
    state: present

- name: Start Jenkins
  service:
    name: jenkins
    enabled: true
    state: started

- name: Sleep for 30 seconds and continue with play
  wait_for: timeout=30

- name: Get init password Jenkins
  shell: cat /var/lib/jenkins/secrets/initialAdminPassword
  changed_when: false
  register: result

- name: Print init password Jenkins
  debug:
    var: result.stdout